[project]
name = "quanutum-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "qiskit[visualization]>=1.3.0",
    "qiskit-ibm-runtime>=0.33.2",
    "ipykernel>=6.29.5",
    "qiskit-aer>=0.15.1",
]
